#!/bin/sh

# Create /etc/apt/sources.list.d/devuan.list during the configure stage
#
# This script will make a best-effort attempt at guessing the needed suite and
# dist values, falling back to sane defaults should the attempt fail.
# No changes will be made if the file already exists.

set -e

case "$1" in
    configure)
    # Assign default values.
    suite="stable"
    dists="main"

    if [ ! -f /etc/apt/sources.lists.d/devuan.list ]; then
      # Populate dists with values from sources.list where available.
      if [ -f /etc/apt/sources.list ] ; then
         for dist in contrib non-free; do
            if grep -q '^[^#]* '$dist /etc/apt/sources.list; then
               dists="$dists $dist"
            fi
         done
      fi

      # Populate suite with LSB value for release (DISTRIB_RELEASE) where available.      
      if [ -x /usr/bin/lsb_release ] ; then
         suite=$(lsb_release -sr)
      fi

      # Create list file with best values for suite and dists vars.
      echo "deb http://packages.devuan.org/devuan $suite $dists" > /etc/apt/sources.list.d/devuan.list
      echo "deb-src http://packages.devuan.org/devuan $suite $dists" >> /etc/apt/sources.list.d/devuan.list
    fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
