#!/bin/sh

# Create /etc/apt/sources.list.d/devuan.list file. 
# Will attempt to attribute best values to "suite" and "dists" vars, otherwise will use defaults.
# Won't do anything if that file already exists.

set -e

case "$1" in
    configure)
    # Attribute default values.
    suite="stable"
    dists="main"
    if [ ! -f /etc/apt/sources.lists.d/devuan.list ]; then
      if [ -f /etc/apt/sources.list ] ; then
	 # Extract targets from existing sources.list file when available, add to "dists" var if they are not yet included.
         for dist in contrib non-free; do
            if grep -q '^[^#]* '$dist /etc/apt/sources.list; then
               dists="$dists $dist"
            fi
         done
      fi
      
      if [ -x /usr/bin/lsb_release ] ; then
	 # Attribute LSB value for release (DISTRIB_RELEASE) to var "suite" if available.
         suite=$(lsb_release -sr)
      fi
      # Create list file with best values for "suite" and "dists" vars.
      echo "deb http://packages.devuan.org/devuan $suite $dists" > /etc/apt/sources.list.d/devuan.list
      echo "deb-src http://packages.devuan.org/devuan $suite $dists" >> /etc/apt/sources.list.d/devuan.list
    fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
